menu:
  en:
    - {name: 'about', url: 'about', folder: 'en', file: 'facts.html'}
    - {name: 'guide', url: 'guide', folder: 'en', file: 'facts.html'}
    - {name: 'toolkit', url: 'toolkit', folder: 'en', file: 'facts.html'}
    - {name: 'links', url: 'links', folder: 'en', file: 'facts.html'}
    - {name: 'faq', url: 'faq', folder: 'en', file: 'facts.html'}
    - {name: 'credits', url: 'credits', folder: 'en', file: 'facts.html'}
  fr:
    - {name: 'à propos', url: 'à_propos', folder: 'fr', file: 'facts.html'}
    - {name: 'guide', url: 'guide', folder: 'fr', file: 'facts.html'}
    - {name: 'boîte à outils', url: 'boîte_à_outils', folder: 'fr', file: 'facts.html'}
    - {name: 'liens', url: 'liens', folder: 'fr', file: 'facts.html'}
    - {name: 'crédits', url: 'crédits', folder: 'fr', file: 'facts.html'}
